
class Sensive:
    SQLALCHEMY_DATABASE_URI = "sqlite:///data.sqlite"
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    DEBUG = True
    JWT_SECRET_KEY = "VBDGFEIBSIVBHRIAZBHRIGNBARHBGIUAHORDFNGIUAIRBGUIOB\ADUBGOABRUGBADBGFUBawor4tgboaBRDGOABROGBARGB"

    MAIL_SERVER = "smtp.sendgrid.net"
    MAIL_PORT = 587
    MAIL_USERNAME = "apikey"
    MAIL_PASSWORD = "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"
    MAIL_USE_TLS = True
    MAIL_USE_SSL = False

sen = Sensive()