"""empty message

Revision ID: 2ee21fa48608
Revises: 
Create Date: 2022-07-07 20:22:07.734233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee21fa48608'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('endereço', sa.String(length=100), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('validade', sa.String(length=20), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('localEstoque', sa.String(length=6), nullable=True),
    sa.Column('localBalcao', sa.String(length=6), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('receita', sa.Boolean(), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lote')
    )
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('endereço', sa.String(length=100), nullable=True),
    sa.Column('receita', sa.Float(), nullable=True),
    sa.Column('lucro', sa.Float(), nullable=True),
    sa.Column('horaAbre', sa.String(length=16), nullable=True),
    sa.Column('horaFecha', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endereço')
    )
    op.create_table('cliente_unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.Integer(), nullable=True),
    sa.Column('unidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['unidade'], ['unidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.Column('endereço', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=16), nullable=True),
    sa.Column('cargo', sa.String(length=30), nullable=True),
    sa.Column('genero', sa.String(length=16), nullable=True),
    sa.Column('unidadetrab', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidadetrab'], ['unidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('avaliaçao', sa.Float(), nullable=True),
    sa.Column('delivery', sa.Boolean(), nullable=True),
    sa.Column('clientecomprou', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clientecomprou'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda', sa.Integer(), nullable=True),
    sa.Column('produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['venda'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda_produto')
    op.drop_table('venda')
    op.drop_table('funcionario')
    op.drop_table('cliente_unidade')
    op.drop_table('unidade')
    op.drop_table('produto')
    op.drop_table('cliente')
    # ### end Alembic commands ###
